### ISSUE TITLE
Auto height row for fixed colum

### ISSUE THREAD

**Issue by stickpro** [jiahengaa/BeeGridTable#1]
Hello posible add height row no fixed colum for  fixed column example 
![image](https://user-images.githubusercontent.com/25886722/100079952-54d14c80-2e56-11eb-83fd-8fb389489f6c.png)

**Comment by jiahengaa** [comment]
Please update beegridtable to Version  1.1.4 . @stickpro ，Thanks for your reminding.
![image](https://user-images.githubusercontent.com/9588909/100401731-4755d580-3095-11eb-9f14-2b4df47f1724.png)

**Comment by stickpro** [comment]
@jiahengaa thank you!!
