### ISSUE TITLE
Let me ask you some questions.

### ISSUE THREAD

**Issue by hinoko58** [jiahengaa/BeeGridTable#10]
1. How can I separate the column header and cell align?
2. Is it possible to do the paging process on the server side?

Thank you.

**Comment by jiahengaa** [comment]
I have added a new alignment example, please refer to using.Hope it helps you.

Align Example: http://beegridtable.com/custom-column-align

Paging can be done on the server side, then please disable the paging function of Beegridtable, and use your own paging component combined with the server side to complete this function
