### ISSUE TITLE
Default sorting doesn't work

### ISSUE THREAD

**Issue by Belephor92** [jiahengaa/BeeGridTable#14]
Hi! In your Overview example you have a default ascending sorting for the (arrow down is on building column)
To expect is that it would go down from A999...A998 etc. But the row is Ascending from A1...A2 etc..
I reproduced it by following code for a column
        {
          title: "updatedAt",
          key: "updatedAt",
          type: "date",
          dateType: "datetime",
          format: "dd-MM-yyyy HH:mm",
          align: "center",
          resizable: "true",
          sortable: "true",
          sortType: "desc"
        }
 
Would be great to enable default sorting if sortType is set!
Great work by the way :)

**Comment by jiahengaa** [comment]
please update to v1.4.0
