### ISSUE TITLE
Filter with select boxes does not work

### ISSUE THREAD

**Issue by Belephor92** [jiahengaa/BeeGridTable#15]
Hi there!

I built a table with a select filter header and also select boxes in its column data.
Following problem occurs:
When I select a value in the header, the column is not filtered by that values. I can't filter for these select box values in your example aswell provided in http://www.beegridtable.com/custom-filter

**Screenshots:**
![image](https://user-images.githubusercontent.com/68380448/108720418-144ea100-7521-11eb-8be4-a354f748a52c.png)
![image](https://user-images.githubusercontent.com/68380448/108720450-1ca6dc00-7521-11eb-95d3-34b5a3ba0b91.png)

Here is the snipped i use for my table:
`  <template
          slot="hreviewState"
          slot-scope="{ column, doSortAndFilter }"
        >
          <Select
            v-model="column.selectedReviewState"
            transfer
            clearable
            style="width: 150px"
            @on-change="filterStateSelectChange(column, doSortAndFilter)"
          >
            <Option
              v-for="item in reviewStates"
              :key="item"
              :value="item"
            >
              {{ item }}
            </Option>
          </Select>
        </template>
        
        <template
          slot="reviewState"
          slot-scope="{ row }"
        >
          <Select
            v-model="row.reviewState"
            style="width: 140px"
            @on-change="changeReviewState(row, $event)"
          >
            <Option
              v-for="item in reviewStates"
              :key="item"
              :value="item"
            >
              {{ item }}
            </Option>
          </Select>
        </template>`

**Comment by jiahengaa** [comment]
> Hi there!
> 
> I built a table with a select filter header and also select boxes in its column data.
> Following problem occurs:
> When I select a value in the header, the column is not filtered by that values. I can't filter for these select box values in your example aswell provided in http://www.beegridtable.com/custom-filter
> 
> **Screenshots:**
> ![image](https://user-images.githubusercontent.com/68380448/108720418-144ea100-7521-11eb-8be4-a354f748a52c.png)
> ![image](https://user-images.githubusercontent.com/68380448/108720450-1ca6dc00-7521-11eb-95d3-34b5a3ba0b91.png)
> 
> Here is the snipped i use for my table:
> ` <template slot="hreviewState" slot-scope="{ column, doSortAndFilter }" > <Select v-model="column.selectedReviewState" transfer clearable style="width: 150px" @on-change="filterStateSelectChange(column, doSortAndFilter)" > <Option v-for="item in reviewStates" :key="item" :value="item" > {{ item }} </Option> </Select> </template> <!-- reviewState row template --> <template slot="reviewState" slot-scope="{ row }" > <Select v-model="row.reviewState" style="width: 140px" @on-change="changeReviewState(row, $event)" > <Option v-for="item in reviewStates" :key="item" :value="item" > {{ item }} </Option> </Select> </template>`

This example only does a custom filter for the Sex column. Your custom filter column can refer to the implementation of the sex column in the example http://www.beegridtable.com/custom-filter
