### ISSUE TITLE
¿How can I overwrite the method pagination so that every time I change the page, I make a call to my API?

### ISSUE THREAD

**Issue by fbarriosCL** [jiahengaa/BeeGridTable#16]
Hello, how can I connect pagination section with my API, for example: 

I have my endpoint with attributes of pagination:

```
data: [{id: 9, name: null, total: "200550.0", neto: null, taxes_id: null, type_movement: "",…},…]
per_page: 25
total_items: 765
total_pages: 31 
```
The attribute data only returns array with 25 results, which is what I send as attribute data `:data="data"`.

```
<BeeGridTable
      border
      height="560"
      :showFilter="false"
      :showSummary="false"
      :columns="columns"
      :data="data"
      ....

```
It should show 765 results instead of 25 :(

```Total 25 items , the filter result 25 items    ```

¿How can I overwrite the method so that every time I change the page, I make a call to my API?

**Comment by jiahengaa** [comment]
hi @fbarriosCL 
Thanks
please update to v1.5.2
For details, please see 
http://beegridtable.com/serverFilterAndSortAndPage
