### ISSUE TITLE
Releases on GitHub

### ISSUE THREAD

**Issue by gmasil** [jiahengaa/BeeGridTable#17]
I am using vue.js without node and currently using version 1.1.2 from GitHub releases.
Could you do a release of the current version here as well?

**Comment by jiahengaa** [comment]
@gmasil  https://github.com/jiahengaa/BeeGridTable/releases/tag/V1.5.2

**Comment by gmasil** [comment]
Thank you very much!
I am already working on the migration to work with node, but that is all new to me as a backend developer, so it takes time. You are really helping me out here in the meantime :)
