### ISSUE TITLE
Missing attributes in lang folder

### ISSUE THREAD

**Issue by fbarriosCL** [jiahengaa/BeeGridTable#4]
Hello I was checking the translations at the time of implementing the table, and attributes are missing for example in **es-ES**

https://github.com/jiahengaa/BeeGridTable/blob/main/src/locale/lang/es-ES.js#L17

missing attributes:

```
filterContain: "Contiene",
filterNotContain: "No contienee",
filterStartWith: "Empezar con",
filterEndWith: "Terminar con",
filterResultL: ", el resultado del filtro",
filterResultR: " items"
```

or I'll send you a pull request?

**Comment by jiahengaa** [comment]
> Hello I was checking the translations at the time of implementing the table, and attributes are missing for example in **es-ES**
> 
> https://github.com/jiahengaa/BeeGridTable/blob/main/src/locale/lang/es-ES.js#L17
> 
> missing attributes:
> 
> ```
> filterContain: "Contiene",
> filterNotContain: "No contienee",
> filterStartWith: "Empezar con",
> filterEndWith: "Terminar con",
> filterResultL: ", el resultado del filtro",
> filterResultR: " items"
> ```
> 
> or I'll send you a pull request?

Thanks a lot, @fbarriosCL !I'll add it later and release the new version 1.1.5.

**Comment by fbarriosCL** [comment]
Sorry
filterNotContain: "No contienee" is filterNotContain: "No contiene", only
one "e"

Felipe Barrios L
CEO - Founder Backtrack Academy <http://www.backtrackacademy.com>
Developer Ruby on rails.
+56 9 42 91 07 70
Linkedin <https://www.linkedin.com/pub/felipe-barrios-leyton/45/34a/732>  |
Github <https://github.com/fbarriosCL>
