### ISSUE TITLE
Safari and MIdori browser

### ISSUE THREAD

**Issue by stickpro** [jiahengaa/BeeGridTable#5]
Hi some bug if use safari or midori(analog safari for linux) 
header not have current height
![image](https://user-images.githubusercontent.com/25886722/103092329-ef64ad00-4607-11eb-8857-3510d0d68750.png)

**Comment by jiahengaa** [comment]
> Hi some bug if use safari or midori(analog safari for linux)
> header not have current height
> ![image](https://user-images.githubusercontent.com/25886722/103092329-ef64ad00-4607-11eb-8857-3510d0d68750.png)

I checked in midori that the latest version does not have this problem.

The environment is as follows:
win10
midori
Beegridtable v1.16

![image](https://user-images.githubusercontent.com/9588909/103131665-9dda2200-46dc-11eb-8581-115f6c94c745.png)

ubuntu
midori
Beegridtable v1.16
![image](https://user-images.githubusercontent.com/9588909/103131707-c5c98580-46dc-11eb-9363-754dc39fc93a.png)

**Comment by stickpro** [comment]
![image](https://user-images.githubusercontent.com/25886722/103132438-93f0f880-46b5-11eb-9762-35ee3f472bb2.png)

arch linux midori 9.0

**Comment by stickpro** [comment]
![image](https://user-images.githubusercontent.com/25886722/103132828-b8e66b00-46b7-11eb-9f85-d3e24297a421.png)
safari, macOS Mojave

**Comment by stickpro** [comment]
may be u try install epiphany browser in linux the problem is also present
![image](https://user-images.githubusercontent.com/25886722/103132874-1975a800-46b8-11eb-91f2-fab2cb5cfe83.png)

**Comment by stickpro** [comment]
Thanks for fix! But there is one more bug with width row and header
![image](https://user-images.githubusercontent.com/25886722/103277144-67045480-49d9-11eb-92b3-1d7bc4a3f9c2.png)

**Comment by jiahengaa** [comment]
@stickpro please update to beegridtable v1.2.1, and need add `import "beegridtable/dist/styles/beegridtable.css";` in main.js.

Installation: http://beegridtable.com/install

**Comment by stickpro** [comment]
ofc i update packege this bug works for sustom header

![image](https://user-images.githubusercontent.com/25886722/103281197-493bed00-49e3-11eb-8618-729871b1a995.png)

**Comment by jiahengaa** [comment]
> ofc i update packege this bug works for custom header
> 
> ![image](https://user-images.githubusercontent.com/25886722/103281197-493bed00-49e3-11eb-8618-729871b1a995.png)

Wait a minutes.I'll tell you why and how to fix.

**Comment by jiahengaa** [comment]
After referring to the following related cases, you can use minwidth to replace width in the column width definition

https://github.com/ElemeFE/element/issues/3322#issuecomment-718610584
https://github.com/ElemeFE/element/pull/2207

your code should look like this:

```
export default {
  data() {
    return {
      columns: [
        {
          title: "编号",
          key: "code",
          minWidth: 150,
          resizable: true,
        },
        {
          title: "姓名",
          key: "name",
          minWidth: 150,
        },
        {
          title: "性别",
          slot: "sex",
          key: "sex",
          minWidth: 150,
          resizable: true,
        },
        { title: "年龄", key: "age", minWidth: 150, resizable: true },
        {
          title: "分组",
          slot: "group",
          key: "groupName",
          resizable: true,
        },
        {
          title: "观察状态",
          slot: "state",
          key: "state",
          minWidth: 200,
        },
        {
          title: "操作",
          slot: "op",
          key: "op",
          minWidth: 150,
        },
      ],
    };
  },
};

```

This will work in safari ！
