### ISSUE TITLE
Nuxt Intallation [@jiahengaa - you can extend your README by this description]

### ISSUE THREAD

**Issue by gustawdaniel** [jiahengaa/BeeGridTable#8]
1. Install

```
npm i beegridtable
```

2. Create plugin `plugins/bee-grid-table.ts` with content:

```
import Vue from "vue";
import BeeGridTable from "beegridtable";

import 'beegridtable/dist/styles/beegridtable.css';
//@ts-ignore
import BeeLocale from "beegridtable/src/locale"

Vue.use(BeeGridTable, {
  locale: BeeLocale,
  capture: true,
});
```

3. In `nuxt.config.js` register plugin:

```
  plugins: [
    {src: '~/plugins/bee-grid-table', ssr: false}
  ],
```

You can't omit `{ssr:false}` option and use

```
  plugins: [
    '~/plugins/bee-grid-table'
  ],
```

because of you will see error:

> Cannot use import statement outside a module

https://stackoverflow.com/questions/64132293/cannot-use-import-statement-outside-a-module-using-nuxtjs

4. In your component use it:

```
<template>
  <div>
    <client-only placeholder="Loading...">
      <BeeGridTable :columns="columns" :data="rows"/>
    </client-only>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'index',
  computed: {
    columns() {
      return [
        {
          title: "Name",
          key: "name",
          align: "center",
        }
      ]
    },
    rows() {
      return [{name: 'A'}, {name: 'B'}]
    }
  }
})
</script>
```

**Comment by jiahengaa** [comment]
Thank you very much for your advice

**Comment by jiahengaa** [comment]
http://beegridtable.com/install
Has been updated to the installation document, thank you for your help !

![image](https://user-images.githubusercontent.com/9588909/105444115-35b13880-5ca8-11eb-9cf9-92b2b7c2eed0.png)
