### ISSUE TITLE
How to add per page number different than 10

### ISSUE THREAD

**Issue by gustawdaniel** [jiahengaa/BeeGridTable#9]
If you have multi page docs, you can add searcher like

https://www.algolia.com/

to make searching in docs easier.

**Comment by gustawdaniel** [comment]
I found in 

```
/node_modules/beegridtable/src/components/table/table.vue
```

parameter `currentSize` in `data` but I can't define it my component.

**Comment by gustawdaniel** [comment]
I recommend copy interface from:

https://vuetifyjs.com/en/components/data-tables/#usage

```
    <v-data-table
      :headers="headers"
      :items="rows"
      :items-per-page="-1"
      class="elevation-1"
    >

    </v-data-table>
```

**Comment by jiahengaa** [comment]
> If you have multi page docs, you can add searcher like
> 
> https://www.algolia.com/
> 
> to make searching in docs easier.

Great idea, but inconsistent with the original intention of beegridtable.
